project:
  type: website
  output-dir: docs

resources:
  - labs/*.txt
website:
  title: "Econometrics and Analytics"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Labs"
        menu:
          - text: "Part 1"
            href: labs/part001.qmd
          - text: "Part 2"
            href: labs/part002.qmd
          - text: "Part 3"
            href: labs/part003.qmd
          - text: "Part 4"
            href: labs/part004.qmd
          - text: "Part 5"
            href: labs/part005.qmd
          - text: "Part 6"
            href: labs/test001_with_mcq.qmd
  sidebar:
    style: "floating"
    contents:
      - index.qmd
      - section: "Labs"
        contents:
          - labs/part001.qmd
          - labs/part002.qmd
          - labs/part003.qmd
          - labs/part004.qmd
          - labs/part005.qmd
          - labs/test001_with_mcq.qmd

format:
  html:
    theme: cosmo
    toc: true
    page-layout: full
    include-after-body: _includes/assistant.html
